base_commit: d2c135da4c75079e45661ec609bd72f27dddf2a9
created_at: '2020-06-25T21:05:18Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13111:latest
instance_id: django__django-13111
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
