base_commit: 94525bbaf417476dbe9a70b98801ae04aceaebf3
created_at: '2019-09-12T15:07:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-3302:latest
instance_id: pydata__xarray-3302
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
