base_commit: 905044f26df65188c6c612695c3370fcc2d007f0
created_at: '2022-12-02T09:57:52Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 8dd8eeb80248cea4360c753847bd622e8652e059
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pyvista_1776_pyvista-3675:latest
instance_id: pyvista__pyvista-3675
log_parser: parse_log_pyvista
repo: pyvista/pyvista
split: dev
version: '0.38'
