base_commit: 51407623e4f491f00e3b465626dd5c4b55860bd0
created_at: '2018-07-17T15:42:55Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 55bf5d93e5674f13a1134d93a11fd0cd11aabcd1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-11596:latest
instance_id: scikit-learn__scikit-learn-11596
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.20'
