base_commit: 8c0c0235b6a23a0d69cd77286d0212de90d4af44
created_at: '2020-01-30T17:11:15Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12394:latest
instance_id: django__django-12394
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
