base_commit: b4bf5168621f0a4bf7cca795862e2b5c139fc8cb
created_at: '2021-12-23T23:10:43Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 3b2fbaec045697d53bdd4435e59dbfc2b286df4b
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pylint-dev_1776_pylint-5595:latest
instance_id: pylint-dev__pylint-5595
log_parser: parse_log_pylint
repo: pylint-dev/pylint
split: test
version: '2.13'
