base_commit: 48c17807a99f7a4341c74db19e16a37b010827c2
created_at: '2019-02-08T02:22:31Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 419a78300f7cd27611196e1e464d50fd0385ff27
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-10957:latest
instance_id: django__django-10957
log_parser: parse_log_django
repo: django/django
split: test
version: '3.0'
