base_commit: 3419079fb0d1f0eecd845eff0d12b367d34cd5e9
created_at: '2020-05-16T07:58:26Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 5afc77ee27fc01c57165ab260d3a76751f9ddb35
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-7670:latest
instance_id: sphinx-doc__sphinx-7670
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.1'
