base_commit: cfd428afc5b6e25bbbe4bc92067f857fa9658442
created_at: '2023-01-11T16:39:30Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1e8a5b833d1b58f3ab84099c4582239af854b23a
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-25363:latest
instance_id: scikit-learn__scikit-learn-25363
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '1.3'
