base_commit: a4e6030904df63b3f10aa0729b86dc6942b0458e
created_at: '2020-05-13T22:02:49Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12910:latest
instance_id: django__django-12910
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
