base_commit: a5c24f01e9b420968f5fda0d5c46ce2a4cf2c867
created_at: '2019-11-22T09:31:54Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: b91d178868d193afd56f8e3b013661a473d699c3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-823:latest
instance_id: pvlib__pvlib-python-823
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.6'
