base_commit: 9ca22c7733efeeb140b75585c6387ef2cb861d19
created_at: '2020-10-27T18:27:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13617:latest
instance_id: django__django-13617
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
