base_commit: 27872b83b0932cc419116f79e442963cced935bb
created_at: '2020-08-21T16:27:41Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 6e5148f59c5050e8f7a0084b7ae39e93b80f72e6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-1026:latest
instance_id: pvlib__pvlib-python-1026
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.7'
