base_commit: 7fa1a93c6c8109010a6ff3f604fda83b604e0e97
created_at: '2020-02-05T10:02:56Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12419:latest
instance_id: django__django-12419
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
