base_commit: 3ea1ec84cc610f7a9f4f6b354e264565254923ff
created_at: '2020-11-22T16:24:25Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 3f560cd67239f75840cc7a439ab54d8509c855f6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-8474:latest
instance_id: sphinx-doc__sphinx-8474
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.4'
