base_commit: 9cc743d0c82e019306d80eb8a83f86f8c6244610
created_at: '2020-01-31T06:41:25Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12396:latest
instance_id: django__django-12396
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
