base_commit: 93d836fcdb38c6b3235f785adc45b34eb2a64a9e
created_at: '2020-01-27T08:27:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 28b41c73c12b70d6ad9f6e45109a80649c4456da
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-18477:latest
instance_id: sympy__sympy-18477
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.6'
