base_commit: d7bddf4f882fe5887638cf3336e7b2f4e989020b
created_at: '2022-01-31T05:35:02Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 9a6104eab0ea7ac191a09c24f3e2d79dcd66bda5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-22969:latest
instance_id: sympy__sympy-22969
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.11'
