base_commit: 9ec5a15823dcb924a5cca322f9f97357f9428345
created_at: '2018-10-25T21:53:00Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7813f7efb5b2012412888b69e73d76f2df2b50b6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-12462:latest
instance_id: scikit-learn__scikit-learn-12462
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.21'
