base_commit: a061ada48efccf0845acae17009553e01764452b
created_at: '2019-02-11T21:34:25Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 7813f7efb5b2012412888b69e73d76f2df2b50b6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-13135:latest
instance_id: scikit-learn__scikit-learn-13135
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.21'
