base_commit: 16743c6faf5cb8433bf9f7702ae70d002a96caaf
created_at: '2022-06-27T21:58:57Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: cdf311e0714e611d48b0a31eb1f0e2cbffab7f23
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-13404:latest
instance_id: astropy__astropy-13404
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '5.0'
