base_commit: 71ae1ab0123582cc5bfe0f7d5f4cc19a9412f396
created_at: '2020-09-14T07:49:15Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13417:latest
instance_id: django__django-13417
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
