base_commit: 3a9f192b131f7a9b0fe5783c684b23015fa67cc8
created_at: '2020-08-31T08:55:35Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13371:latest
instance_id: django__django-13371
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
