base_commit: eb926a1d0c1158bf43f01eaf673dc84416b5ebb1
created_at: '2020-12-21T07:42:53Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 3ac1464b8840d5f8b618a654f9fbf09c452fe969
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-20639:latest
instance_id: sympy__sympy-20639
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.8'
