base_commit: 9951491e0b849834c369de522de2df8172a2e298
created_at: '2022-10-24T05:12:40Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 087ebbb78668bdf5d2d41c3b2553e3f29ce75be1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-7203:latest
instance_id: pydata__xarray-7203
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '2022.09'
