base_commit: 2feb0b43b64012ac982a9d07af85002b43b59226
created_at: '2020-07-08T16:50:21Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: f92fa6443fe6f457ab0c26d41eb229e825fda5e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-7930:latest
instance_id: sphinx-doc__sphinx-7930
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.2'
