base_commit: d951e55bc3419dbda809ed0aca17addeed8e9e30
created_at: '2022-04-17T15:30:43Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 60775ec4c4ea08509eee4b564cbf90f316021aff
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-10360:latest
instance_id: sphinx-doc__sphinx-10360
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '5.0'
