base_commit: 78f163a4fb3937aca2e71786fbdd51a0ef39629e
created_at: '2022-11-16T19:16:42Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0fbdb9784da915fce5dcc1fe82bac9b4785749e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16302:latest
instance_id: django__django-16302
log_parser: parse_log_django
repo: django/django
split: test
version: '4.2'
