base_commit: ab36f3cc6f91f1e4903a3f4b31501cb7fefe4555
created_at: '2013-04-30T20:05:30Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: d8268fb7b44da7b8aa225eb1ca6fbdb4f9dc2457
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.psf_1776_requests-1339:latest
instance_id: psf__requests-1339
log_parser: parse_log_requests
repo: psf/requests
split: test
version: '1.2'
