base_commit: 8328811f048fed0dd22573224def8c65410c9f2e
created_at: '2020-05-04T21:29:23Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12856:latest
instance_id: django__django-12856
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
