base_commit: 3d8a56298c71a67dedb0472f94e3746d04ddd117
created_at: '2019-08-25T17:17:51Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-17512:latest
instance_id: sympy__sympy-17512
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
