base_commit: c90ab30fa1305481024b9c3c50b5a6ed6cd9a2f5
created_at: '2019-11-29T17:06:08Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12161:latest
instance_id: django__django-12161
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
