base_commit: fa5e7e46d875d4143510944f19d79df7b1739bab
created_at: '2020-04-04T18:58:49Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12663:latest
instance_id: django__django-12663
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
