base_commit: 53e0d95cb10cba5827751657e487f792afd94329
created_at: '2023-02-10T17:30:04Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1e8a5b833d1b58f3ab84099c4582239af854b23a
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-25589:latest
instance_id: scikit-learn__scikit-learn-25589
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '1.3'
