base_commit: ecea98f9c965fbb25d2dfb1fdc23784364aa5657
created_at: '2019-07-02T18:11:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-14237:latest
instance_id: scikit-learn__scikit-learn-14237
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
