base_commit: 7c4f3965098baad2396e24501e09237425a7bd6f
created_at: '2022-01-22T01:56:48Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 647480166bfe7532e8c471fef0146e3a17e6c0c9
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-15347:latest
instance_id: django__django-15347
log_parser: parse_log_django
repo: django/django
split: test
version: '4.1'
