base_commit: e2d9d66a22f9004c0349f6aa9f8762fa558bdee8
created_at: '2020-01-06T11:14:37Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12281:latest
instance_id: django__django-12281
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
