base_commit: f997b5e6ae85e2df2342b1a7812fe8130206c957
created_at: '2019-10-30T09:34:35Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-11991:latest
instance_id: django__django-11991
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
