base_commit: 5c73fbb6a93ee214678f02ba4027f18dff49337b
created_at: '2021-04-21T05:40:18Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 475cffd1d64c690cdad16ede4d5e81985738ceb4
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-14291:latest
instance_id: django__django-14291
log_parser: parse_log_django
repo: django/django
split: test
version: '4.0'
