base_commit: f14561da80c263b867b51e27a75c4f9cdacfeb29
created_at: '2021-06-16T07:23:24Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 9a2c3c4a1559e37e95fdee88c128bb116642c897
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-9350:latest
instance_id: sphinx-doc__sphinx-9350
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '4.1'
