base_commit: 2276ec8c21655b05bb44e14e236b499aa5d01f5b
created_at: '2023-02-27T02:04:43Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 4a72da71001f154ea60906a2f74898d32b7322a7
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16600:latest
instance_id: django__django-16600
log_parser: parse_log_django
repo: django/django
split: test
version: '5.0'
