base_commit: f98d6f065db2ad1f8911cb22aa04b4e0210ecee4
created_at: '2021-01-19T22:54:10Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-4827:latest
instance_id: pydata__xarray-4827
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
