base_commit: bcc986e7d217f017130385b89cbda837f3e650ac
created_at: '2021-03-25T12:55:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: cbdcfb09feb4883de91de142956c3be6ac7f827d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sqlfluff_1776_sqlfluff-891:latest
instance_id: sqlfluff__sqlfluff-891
log_parser: parse_log_sqlfluff
repo: sqlfluff/sqlfluff
split: dev
version: '0.4'
