base_commit: f80068c86b9fc14c9395b52fac39a8e9fae5ef27
created_at: '2021-02-23T18:12:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ef8ad2fee9840a77d14b0dfd17fc489dd85c9b91
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-1176:latest
instance_id: pvlib__pvlib-python-1176
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.8'
