base_commit: 069bee7c1232458a0f13c2e30daa8df99dbd3680
created_at: '2017-02-27T09:30:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 419a78300f7cd27611196e1e464d50fd0385ff27
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-8119:latest
instance_id: django__django-8119
log_parser: parse_log_django
repo: django/django
split: test
version: '3.0'
