base_commit: b13b02c311c18c2041782bcdaadd08b8fd3f216b
created_at: '2019-11-02T20:17:27Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-15495:latest
instance_id: scikit-learn__scikit-learn-15495
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
