base_commit: c863ed3d57e3b5ceeb4e7e8001c96aad7110c605
created_at: '2019-03-28T08:05:48Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7813f7efb5b2012412888b69e73d76f2df2b50b6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-13536:latest
instance_id: scikit-learn__scikit-learn-13536
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.21'
