base_commit: c121e32082edaff817d9f69dec0c24855dc0186f
created_at: '2022-03-03T01:53:38Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 647480166bfe7532e8c471fef0146e3a17e6c0c9
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-15474:latest
instance_id: django__django-15474
log_parser: parse_log_django
repo: django/django
split: test
version: '4.1'
