base_commit: d49a6f13af2f22228d430ac64ac2b518937800d0
created_at: '2019-07-28T13:47:05Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-14496:latest
instance_id: scikit-learn__scikit-learn-14496
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
