base_commit: 4a9e54962a29c12a8b103d75f838e0e795a6974d
created_at: '2022-12-18T17:13:51Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: d25872b0fc99dbf7e666a91f59bd4ed125186aa1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.mwaskom_1776_seaborn-3190:latest
instance_id: mwaskom__seaborn-3190
log_parser: parse_log_seaborn
repo: mwaskom/seaborn
split: test
version: '0.12'
