base_commit: f8e46e9e741f253803e9b8be03287e5dd16abd4d
created_at: '2019-02-09T00:17:24Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 73b3f90093754c5ed1561bd885242330e3583004
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-15948:latest
instance_id: sympy__sympy-15948
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.4'
