base_commit: 25cbd1e6aa4178c31d60e3900a5bd4aa177c01c9
created_at: '2021-09-23T16:43:07Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 647480166bfe7532e8c471fef0146e3a17e6c0c9
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-14890:latest
instance_id: django__django-14890
log_parser: parse_log_django
repo: django/django
split: test
version: '4.1'
