base_commit: 0f182558484ec7964413fc93f6361f0842135b2b
created_at: '2020-10-18T08:25:22Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13556:latest
instance_id: django__django-13556
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
