base_commit: 4aded39b5663d943f6a4809abacfa9cae3d7fb6a
created_at: '2019-08-12T09:31:54Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-14629:latest
instance_id: scikit-learn__scikit-learn-14629
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
