base_commit: 7b8cbc875b862ebb81a9b3415bdee235cca99ca6
created_at: '2019-06-18T13:20:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-14114:latest
instance_id: scikit-learn__scikit-learn-14114
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
