base_commit: 38b233c605489d6e64738b2da99248f677f4a29f
created_at: '2017-12-19T05:32:15Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-13768:latest
instance_id: sympy__sympy-13768
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
