base_commit: 3dca8738cbbbb5674f795169e5ea25e2002f2d71
created_at: '2019-01-28T08:12:14Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 419a78300f7cd27611196e1e464d50fd0385ff27
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-10910:latest
instance_id: django__django-10910
log_parser: parse_log_django
repo: django/django
split: test
version: '3.0'
