base_commit: a9179ab032cda80801e7f67ef20db5ee60989f21
created_at: '2019-04-28T09:13:45Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 419a78300f7cd27611196e1e464d50fd0385ff27
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-11298:latest
instance_id: django__django-11298
log_parser: parse_log_django
repo: django/django
split: test
version: '3.0'
