base_commit: 7e022a7e8ba0f95b65d9acade559da95115ad9e5
created_at: '2019-07-21T02:47:05Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-14430:latest
instance_id: scikit-learn__scikit-learn-14430
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
