base_commit: dc138bcc3af8e2696169caeee5a2010b0c934686
created_at: '2020-04-26T14:58:39Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 28b41c73c12b70d6ad9f6e45109a80649c4456da
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-19201:latest
instance_id: sympy__sympy-19201
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.6'
