base_commit: 34d83416b3e0223b4e8abaa582416812719b81da
created_at: '2017-07-16T08:38:53Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-12977:latest
instance_id: sympy__sympy-12977
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
