base_commit: 2c0a3a103baa547de12e332382d44ee3733d485f
created_at: '2018-02-11T21:58:27Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-14166:latest
instance_id: sympy__sympy-14166
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
