base_commit: a123f8351dc9f7ddfb06c5fafb25fedf6d119ff1
created_at: '2013-11-09T22:49:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 4bceb312f1b99d36a25f2985b5606e98b6f0d8cd
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.psf_1776_requests-1733:latest
instance_id: psf__requests-1733
log_parser: parse_log_requests
repo: psf/requests
split: test
version: '2.0'
