base_commit: 7e15795bf06d362f20257d2e9db378ba8940dc39
created_at: '2020-02-26T17:59:25Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12496:latest
instance_id: django__django-12496
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
