base_commit: 12c50d4004174407a6afc9ab748ba553de42aa07
created_at: '2019-07-26T16:22:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-17273:latest
instance_id: sympy__sympy-17273
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
