base_commit: cdad96e6330cd31185f7496aaf8eb316f2773d6d
created_at: '2021-08-11T15:01:48Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 647480166bfe7532e8c471fef0146e3a17e6c0c9
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-14762:latest
instance_id: django__django-14762
log_parser: parse_log_django
repo: django/django
split: test
version: '4.1'
