base_commit: 82dad44e5bd3776ecb6fd8ded656bc8151d0e63d
created_at: '2021-06-02T15:06:11Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 9a2c3c4a1559e37e95fdee88c128bb116642c897
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-9289:latest
instance_id: sphinx-doc__sphinx-9289
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '4.1'
