base_commit: c32d8f33d8e988a376e44997b8f3606d821f305e
created_at: '2020-10-04T21:16:50Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13490:latest
instance_id: django__django-13490
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
