base_commit: b2b0711b555fa292751763c2df4fe577c396f265
created_at: '2020-08-02T10:02:11Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13265:latest
instance_id: django__django-13265
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
