base_commit: 9f0b959a8c9195d1b6e203f08b698e052b426ca9
created_at: '2019-02-09T02:15:23Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 7813f7efb5b2012412888b69e73d76f2df2b50b6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-13124:latest
instance_id: scikit-learn__scikit-learn-13124
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.21'
