base_commit: faa940608befaeca99db501609c6db796739f30f
created_at: '2017-07-03T22:39:22Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-9274:latest
instance_id: scikit-learn__scikit-learn-9274
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
