base_commit: 356a73cd676e0c3f1a1c3057a6895db0d82a1be7
created_at: '2019-03-19T07:47:15Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 73b3f90093754c5ed1561bd885242330e3583004
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16331:latest
instance_id: sympy__sympy-16331
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.4'
