base_commit: 699c9f0a8e190d463dd828822106250523d38154
created_at: '2021-06-18T13:14:02Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 506ecea8f378dc687d5c504788fc78810a190b7a
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydicom_1776_pydicom-1416:latest
instance_id: pydicom__pydicom-1416
log_parser: parse_log_pydicom
repo: pydicom/pydicom
split: dev
version: '2.1'
