base_commit: c76af9ed6bb89bfba45b9f5bc1e635188278e2fa
created_at: '2017-12-07T00:01:14Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 848c8fa21332abd66b44efe3cb48b72377fb32cc
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-6938:latest
instance_id: astropy__astropy-6938
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '1.3'
