base_commit: df7dd8391148a873d157328a4f0328528a0c4ed9
created_at: '2019-06-14T14:16:17Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-14092:latest
instance_id: scikit-learn__scikit-learn-14092
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
