base_commit: dec525f376a5b62bfc3dd361db057b44e7ebff14
created_at: '2019-05-20T21:24:45Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16864:latest
instance_id: sympy__sympy-16864
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
