base_commit: f83b44075dafa429d59e8755aa47e15577cc49f9
created_at: '2020-06-04T19:49:04Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13022:latest
instance_id: django__django-13022
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
