base_commit: b8a4da8baa1137f173e7035f104067c7d2ffde22
created_at: '2019-11-02T22:28:57Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-15512:latest
instance_id: scikit-learn__scikit-learn-15512
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
