base_commit: 2fac0a18081dcc77fc860c801e5d727dc90435b3
created_at: '2022-07-22T22:05:16Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0fbdb9784da915fce5dcc1fe82bac9b4785749e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-15869:latest
instance_id: django__django-15869
log_parser: parse_log_django
repo: django/django
split: test
version: '4.2'
