base_commit: cfe3008123ed7c9e3f3a4d51d4a22f9d96634e33
created_at: '2022-09-20T11:42:13Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0fbdb9784da915fce5dcc1fe82bac9b4785749e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16076:latest
instance_id: django__django-16076
log_parser: parse_log_django
repo: django/django
split: test
version: '4.2'
