base_commit: c0ef2f616e87e9f924425bcd373ac265f14203cb
created_at: '2019-11-13T23:03:07Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-3527:latest
instance_id: pydata__xarray-3527
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
