base_commit: b34751b7ed02b2cfcc36037fb729d4360480a299
created_at: '2019-05-03T13:24:57Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
- SWE-bench/SWE-bench_Lite
difficulty: <15 min fix
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-13779:latest
instance_id: scikit-learn__scikit-learn-13779
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
