base_commit: cc50b90034a9cda77a8aabedc8a853fe92de60b5
created_at: '2018-01-08T19:05:07Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 55bf5d93e5674f13a1134d93a11fd0cd11aabcd1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-10427:latest
instance_id: scikit-learn__scikit-learn-10427
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.20'
