base_commit: 88b81a06eb635a1596617f8971fa97a84c069e93
created_at: '2020-10-03T13:31:13Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 3b85187ffa3401e88582073c23188c147857a8a3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-8273:latest
instance_id: sphinx-doc__sphinx-8273
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.3'
