base_commit: 754b487f4d892e3d4872b6fc7468a71db4e31c13
created_at: '2022-04-19T06:34:57Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 680edebc686cad664bbed934a490aeafa775f163
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pylint-dev_1776_pylint-6386:latest
instance_id: pylint-dev__pylint-6386
log_parser: parse_log_pylint
repo: pylint-dev/pylint
split: test
version: '2.14'
