base_commit: a1fbd0066219a7a1d14d4d9024d8aeeb5cb8d51a
created_at: '2020-03-09T17:50:56Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 28b41c73c12b70d6ad9f6e45109a80649c4456da
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-18810:latest
instance_id: sympy__sympy-18810
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.6'
