base_commit: 373c6c409c310cb61e1e9c9aff4adba379ffd0b4
created_at: '2016-11-05T11:48:45Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 3545e844885608932a692d952c12cd863e2320b5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-7475:latest
instance_id: django__django-7475
log_parser: parse_log_django
repo: django/django
split: test
version: '1.11'
