base_commit: d250ff08a834bb0ba2b636b0a7d63a4cf33f6e22
created_at: '2017-07-07T20:22:42Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-12906:latest
instance_id: sympy__sympy-12906
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
