base_commit: 6deb592a2fadbf88b7a00a332837a81a3198a830
created_at: '2020-03-25T13:08:37Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 50d2d289e150cb429de15770bdd48a723de8c45d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-7380:latest
instance_id: sphinx-doc__sphinx-7380
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.0'
