base_commit: f91de695585c1fbc7d4f49ee061f64fcb1c2c4d8
created_at: '2019-06-12T21:54:57Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-17022:latest
instance_id: sympy__sympy-17022
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
