base_commit: 42c08ee46539ef44f8658ebb1cbefb408e0d03fe
created_at: '2020-05-14T04:21:52Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12912:latest
instance_id: django__django-12912
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
