base_commit: b185ca184f8dd574531dcc21e797f00537fefa6a
created_at: '2022-04-22T17:32:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: cdf311e0714e611d48b0a31eb1f0e2cbffab7f23
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-13158:latest
instance_id: astropy__astropy-13158
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '5.0'
