base_commit: 8dcb12a6cf500e8738d6729ab954a261758f49ca
created_at: '2016-07-15T21:40:49Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 50b81f9f6be151014501ffac44e5dc6b2416938f
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-11400:latest
instance_id: sympy__sympy-11400
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.0'
