base_commit: faf27fee1fcbae3b7056bd02f9e98b7d6e5cb42d
created_at: '2023-01-28T00:30:44Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ef8ad2fee9840a77d14b0dfd17fc489dd85c9b91
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-1653:latest
instance_id: pvlib__pvlib-python-1653
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.8'
