base_commit: 13993e0f38d5f272236887ef22b491eb1b20dce9
created_at: '2020-03-19T10:20:11Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12588:latest
instance_id: django__django-12588
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
