base_commit: e1bac62d2f3df7bcba25d58ed5e83d89f9a6be98
created_at: '2019-10-31T03:34:40Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1affc211d8b93024fa3e163584f235975d3536ed
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pyvista_1776_pyvista-432:latest
instance_id: pyvista__pyvista-432
log_parser: parse_log_pyvista
repo: pyvista/pyvista
split: dev
version: '0.22'
