base_commit: d466cc25a78b442cd4ccaafae4adef9a7f1e4012
created_at: '2020-07-11T16:00:30Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 634cde9506eb1f48dec3ec77974ee8dc952207c6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pytest-dev_1776_pytest-7481:latest
instance_id: pytest-dev__pytest-7481
log_parser: parse_log_pytest
repo: pytest-dev/pytest
split: test
version: '6.0'
