base_commit: 0a14b273517a082603cc157faa88a5ab0ac4cac9
created_at: '2019-08-13T20:05:11Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: b91d178868d193afd56f8e3b013661a473d699c3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-763:latest
instance_id: pvlib__pvlib-python-763
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.6'
