base_commit: 3a0cd2d8cd7b459cdc1e1b97a14f3040ccc1fffc
created_at: '2022-02-12T12:38:10Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 298ccb478e6bf092953bca67a3d29dc6c35f6752
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-12842:latest
instance_id: astropy__astropy-12842
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '4.3'
