base_commit: 10de1a18a0efac0b19b611e40c928250dda688bf
created_at: '2022-04-23T23:40:41Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 9a6104eab0ea7ac191a09c24f3e2d79dcd66bda5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-23413:latest
instance_id: sympy__sympy-23413
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.11'
