base_commit: f52a95cbe694336fe47bc5a42c713bee8ad74d64
created_at: '2021-01-04T11:17:53Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-4759:latest
instance_id: pydata__xarray-4759
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
