base_commit: e56905889c836c736152b11a7e6117a229715975
created_at: '2021-04-08T09:19:30Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-5131:latest
instance_id: pydata__xarray-5131
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
