base_commit: 2aabb71dc8db434122c2e00c9d1313c6f368ce1c
created_at: '2013-05-21T17:51:54Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: d8268fb7b44da7b8aa225eb1ca6fbdb4f9dc2457
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.psf_1776_requests-1376:latest
instance_id: psf__requests-1376
log_parser: parse_log_requests
repo: psf/requests
split: test
version: '1.2'
