base_commit: 649262a406168709686f97694493aa1f717c6c96
created_at: '2023-06-01T14:53:32Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 4a72da71001f154ea60906a2f74898d32b7322a7
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16920:latest
instance_id: django__django-16920
log_parser: parse_log_django
repo: django/django
split: test
version: '5.0'
