base_commit: 59be4993000cc8af2cd9a4176f15398b6a7875d7
created_at: '2020-11-04T20:55:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 506ecea8f378dc687d5c504788fc78810a190b7a
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydicom_1776_pydicom-1255:latest
instance_id: pydicom__pydicom-1255
log_parser: parse_log_pydicom
repo: pydicom/pydicom
split: dev
version: '2.1'
