base_commit: 9adba491a209b2768274cd7f0499c6e41df8c8fa
created_at: '2019-05-29T18:27:02Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-13983:latest
instance_id: scikit-learn__scikit-learn-13983
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
