base_commit: 9ed054279aeffd5b1d0642e2d24a8800389de29f
created_at: '2021-08-29T15:26:24Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 336605b8e4b14c5da9f4d872fb730dc6894edb77
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-9591:latest
instance_id: sphinx-doc__sphinx-9591
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '4.2'
