base_commit: 8b3e714ecf409ed6c9628c3f2a4e033cbfa4253b
created_at: '2020-01-10T19:36:24Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12306:latest
instance_id: django__django-12306
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
