base_commit: c3defb095b1aa7fe23c4bd430fdff2ce6ed6161d
created_at: '2022-11-09T18:11:06Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: dc59c2a5672aacedaf91f0e6129b467eefad331b
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sqlfluff_1776_sqlfluff-4051:latest
instance_id: sqlfluff__sqlfluff-4051
log_parser: parse_log_sqlfluff
repo: sqlfluff/sqlfluff
split: dev
version: '1.3'
