base_commit: e3f77d58f56149f9c8db3b790ef263b9853a9cb5
created_at: '2023-04-18T04:35:29Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: d19de0ecd16d298f9e3bfb91da122734c40c01e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sqlfluff_1776_sqlfluff-4778:latest
instance_id: sqlfluff__sqlfluff-4778
log_parser: parse_log_sqlfluff
repo: sqlfluff/sqlfluff
split: dev
version: '1.4'
