base_commit: 6e95230e0ee183a4fb8803a7e49d7744f0a0025c
created_at: '2018-05-04T18:30:31Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-14699:latest
instance_id: sympy__sympy-14699
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
