base_commit: 1e1417cab24e5602d2d4db85e218d5277f13aeda
created_at: '2017-12-28T07:05:13Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 55bf5d93e5674f13a1134d93a11fd0cd11aabcd1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-10382:latest
instance_id: scikit-learn__scikit-learn-10382
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.20'
