base_commit: d68be0494be8b82365f2a5410c9335e539d8efd6
created_at: '2021-04-26T09:40:46Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 475cffd1d64c690cdad16ede4d5e81985738ceb4
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-14313:latest
instance_id: django__django-14313
log_parser: parse_log_django
repo: django/django
split: test
version: '4.0'
