base_commit: a320c085b75b8d18b3d10e7283a5e7695806bc1a
created_at: '2017-03-07T23:11:25Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 55bf5d93e5674f13a1134d93a11fd0cd11aabcd1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-8554:latest
instance_id: scikit-learn__scikit-learn-8554
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.20'
