base_commit: 7b595569b26f4aa65a74a971ef428f4f071f48c4
created_at: '2023-02-24T18:22:16Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1e8a5b833d1b58f3ab84099c4582239af854b23a
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-25694:latest
instance_id: scikit-learn__scikit-learn-25694
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '1.3'
