base_commit: 4c1b401e8250f9f520b3c7dc369554477ce8b15a
created_at: '2020-01-09T15:43:51Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12304:latest
instance_id: django__django-12304
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
