base_commit: e1ce41b95534f80955e3809fdf5ada61ecb5946f
created_at: '2016-10-29T21:33:54Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 50b81f9f6be151014501ffac44e5dc6b2416938f
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-11788:latest
instance_id: sympy__sympy-11788
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.0'
