base_commit: ac03325b44485e603992a0bb783536a9f8a9152f
created_at: '2017-10-10T13:20:35Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-13429:latest
instance_id: sympy__sympy-13429
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
