base_commit: 596dfba841a2e8c570ab8a916398140f15efd9f5
created_at: '2021-01-17T15:07:20Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 4f8cb861e3b29186b38248fe81e4944fd987fcce
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-8697:latest
instance_id: sphinx-doc__sphinx-8697
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.5'
