base_commit: 2b5c55e45a0fc4e2197a9b8edb482b77c2fa3f85
created_at: '2021-10-30T15:26:46Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 6c6cc8a6f50b18331cb818160d168d7bb9c03e55
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-9799:latest
instance_id: sphinx-doc__sphinx-9799
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '4.3'
