base_commit: d8dfff2ab0edf7a1ca5255eccf45c447b2f9d57e
created_at: '2020-12-03T08:23:13Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13744:latest
instance_id: django__django-13744
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
