base_commit: be6bf6902c199b27f4f001ce3597e521c3a0d0aa
created_at: '2018-07-19T16:56:01Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-11635:latest
instance_id: scikit-learn__scikit-learn-11635
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
