base_commit: 1893b20a7b755004f561037161c242db24e2870c
created_at: '2022-03-14T18:37:44Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ef8ad2fee9840a77d14b0dfd17fc489dd85c9b91
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-1426:latest
instance_id: pvlib__pvlib-python-1426
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.8'
