base_commit: 75410228dfd16e49eb3c0ea30b59b4c0d2ea6b03
created_at: '2020-03-20T07:59:43Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0668164b4ac93a5be79f5b87fae83c657124d9ab
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12591:latest
instance_id: django__django-12591
log_parser: parse_log_django
repo: django/django
split: test
version: '3.1'
