base_commit: 649b28eab6765cd6b2b40c779a18ecafc99b43d7
created_at: '2022-09-17T16:01:21Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0fbdb9784da915fce5dcc1fe82bac9b4785749e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16070:latest
instance_id: django__django-16070
log_parser: parse_log_django
repo: django/django
split: test
version: '4.2'
