base_commit: bd82f01faf4212f6e43f55a1cc6da17956122d8f
created_at: '2021-04-26T19:16:35Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 506ecea8f378dc687d5c504788fc78810a190b7a
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydicom_1776_pydicom-1365:latest
instance_id: pydicom__pydicom-1365
log_parser: parse_log_pydicom
repo: pydicom/pydicom
split: dev
version: '2.1'
