base_commit: 6c19c2ca51746f30fa35668876416c9178487388
created_at: '2020-04-29T03:32:25Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12821:latest
instance_id: django__django-12821
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
