base_commit: ca436e7017ae069a29de19caf71689e9b9b9c452
created_at: '2018-04-15T23:28:27Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 55bf5d93e5674f13a1134d93a11fd0cd11aabcd1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-10982:latest
instance_id: scikit-learn__scikit-learn-10982
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.20'
