base_commit: 3c84edd644fa4db54955e2225a183fa3e0405eb0
created_at: '2019-05-13T14:43:11Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 84818c6d950142927359ffe308c728a0c080ddce
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-718:latest
instance_id: pvlib__pvlib-python-718
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.5'
