base_commit: 966b5b49b6521483f1c90b4499c4c80e80136de3
created_at: '2020-10-29T18:35:54Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13620:latest
instance_id: django__django-13620
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
