base_commit: f0fef96906d80d89e290a780767a92ba85977733
created_at: '2021-05-15T17:28:42Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 9a2c3c4a1559e37e95fdee88c128bb116642c897
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-9234:latest
instance_id: sphinx-doc__sphinx-9234
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '4.1'
