base_commit: a429c3984a14c995584455e51a6f3d7d9c16e914
created_at: '2023-04-27T11:59:59Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 362f6df12abf9bd769d4915fabf955c993ea22cf
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-14701:latest
instance_id: astropy__astropy-14701
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '5.2'
