base_commit: af5ec222ccd24e81f9fec6c34836a4e503e7ccf7
created_at: '2019-04-03T11:25:53Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 419a78300f7cd27611196e1e464d50fd0385ff27
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-11165:latest
instance_id: django__django-11165
log_parser: parse_log_django
repo: django/django
split: test
version: '3.0'
