base_commit: 85440978f517118e78dc15f84e397d50d14c8097
created_at: '2019-02-13T12:55:30Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7813f7efb5b2012412888b69e73d76f2df2b50b6
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-13157:latest
instance_id: scikit-learn__scikit-learn-13157
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.21'
