base_commit: 31d469a5335c81ec4a437e36a861945a6b43d916
created_at: '2021-05-26T23:53:16Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: f9a6f50ec0c74d935c50a6e9c9b2cb0469570d91
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-21527:latest
instance_id: sympy__sympy-21527
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.9'
