base_commit: 514c16e85f7ac2512235f3b6413646627420e969
created_at: '2021-10-12T19:14:35Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 647480166bfe7532e8c471fef0146e3a17e6c0c9
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-14983:latest
instance_id: django__django-14983
log_parser: parse_log_django
repo: django/django
split: test
version: '4.1'
