base_commit: bf47c719719d0e190a99fa2e7f959d5bbb7caf8a
created_at: '2022-09-21T18:49:40Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 0fbdb9784da915fce5dcc1fe82bac9b4785749e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16082:latest
instance_id: django__django-16082
log_parser: parse_log_django
repo: django/django
split: test
version: '4.2'
