base_commit: 44ad84a4332dfb89e810106fef2616a0bc7e47e4
created_at: '2022-01-27T08:43:30Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 3b2fbaec045697d53bdd4435e59dbfc2b286df4b
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pylint-dev_1776_pylint-5730:latest
instance_id: pylint-dev__pylint-5730
log_parser: parse_log_pylint
repo: pylint-dev/pylint
split: test
version: '2.13'
