base_commit: 71a7a76ddff8c01fbfdd166e4ff6f691235925cd
created_at: '2019-05-15T17:26:34Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16840:latest
instance_id: sympy__sympy-16840
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
