base_commit: daac289bed6a780e91a452a0538ad6421c2ed8d5
created_at: '2017-09-11T20:59:50Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-13301:latest
instance_id: sympy__sympy-13301
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
