base_commit: fd4cce73e9d4e7aa5d8a14012d6579861c320cd2
created_at: '2022-06-02T07:54:57Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: de98877e3dc45de8dd441d008f23d88738dc015d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.matplotlib_1776_matplotlib-23188:latest
instance_id: matplotlib__matplotlib-23188
log_parser: parse_log_matplotlib
repo: matplotlib/matplotlib
split: test
version: '3.5'
