base_commit: 7298df0c05168896a9813249b54a2d11f35cfa8f
created_at: '2021-01-05T17:49:05Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-4767:latest
instance_id: pydata__xarray-4767
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
