base_commit: 4c288bc97ea371817199908d0d9b12de9dae327e
created_at: '2023-02-22T14:00:17Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 182ce3dd15dfa3537391c3efaf9c3ff407d134d4
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pallets_1776_flask-4992:latest
instance_id: pallets__flask-4992
log_parser: parse_log_flask
repo: pallets/flask
split: test
version: '2.3'
