base_commit: 0d77d28d1be6758d8d921068c7d54e32befe11b3
created_at: '2020-03-18T18:14:51Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 28b41c73c12b70d6ad9f6e45109a80649c4456da
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-18903:latest
instance_id: sympy__sympy-18903
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.6'
