base_commit: 1757dffac2fa493d7b9a074b84cf8c830a706688
created_at: '2019-07-11T13:16:16Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 1c198a191127c601d091213c4b3292a8bb3054e1
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydata_1776_xarray-3095:latest
instance_id: pydata__xarray-3095
log_parser: parse_log_xarray
repo: pydata/xarray
split: test
version: '0.12'
