base_commit: 38436b6824c079564b8760ea6acfa4c0fd3ee9c3
created_at: '2019-08-15T20:21:09Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7241f5d9db0de589b230bb84212fbb643a7c86c3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydicom_1776_pydicom-933:latest
instance_id: pydicom__pydicom-933
log_parser: parse_log_pydicom
repo: pydicom/pydicom
split: dev
version: '1.3'
