base_commit: 514991036806e9cda2b12cef8ab3184ac373bd6c
created_at: '2023-07-06T20:52:39Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 1113d490ec4a94cdc1b35f45abfdaca9f19fa31e
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pylint-dev_1776_astroid-2240:latest
instance_id: pylint-dev__astroid-2240
log_parser: parse_log_astroid
repo: pylint-dev/astroid
split: dev
version: '3.0'
