base_commit: 9988d5ce267bf0df4791770b469431b1fb00dcdd
created_at: '2020-05-30T06:41:07Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 5afc77ee27fc01c57165ab260d3a76751f9ddb35
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sphinx-doc_1776_sphinx-7748:latest
instance_id: sphinx-doc__sphinx-7748
log_parser: parse_log_sphinx
repo: sphinx-doc/sphinx
split: test
version: '3.1'
