base_commit: 461b740db6ae3d3ab1c5d975b657307f5c630fcb
created_at: '2015-02-28T16:53:27Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 461b740db6ae3d3ab1c5d975b657307f5c630fcb
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.psf_1776_requests-2466:latest
instance_id: psf__requests-2466
log_parser: parse_log_requests
repo: psf/requests
split: test
version: '2.5'
