base_commit: 8fc3b3a96b9f982ed6dc8f626129abee36bcda95
created_at: '2019-03-10T09:11:58Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 73b3f90093754c5ed1561bd885242330e3583004
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16221:latest
instance_id: sympy__sympy-16221
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.4'
