base_commit: 437196da9a386bd4cc62b0ce3f2de4aba468613d
created_at: '2020-05-24T13:20:03Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12965:latest
instance_id: django__django-12965
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
