base_commit: 0e6fea6219618c0da944e6ed686c10f5b1e244a2
created_at: '2021-08-08T05:20:56Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: ef8ad2fee9840a77d14b0dfd17fc489dd85c9b91
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pvlib_1776_pvlib-python-1273:latest
instance_id: pvlib__pvlib-python-1273
log_parser: parse_log_pvlib
repo: pvlib/pvlib-python
split: dev
version: '0.8'
