base_commit: da4929882a0492492549f8dd5a67f262df1ff142
created_at: '2019-05-26T19:03:23Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16901:latest
instance_id: sympy__sympy-16901
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
