base_commit: 415f50298f97fb17f841a9df38d995ccf347dfcc
created_at: '2021-01-04T17:44:23Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 1-4 hours
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13837:latest
instance_id: django__django-13837
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
