base_commit: e2a2ca3eab1defc71aedf4cf3982f7d4793faacf
created_at: '2023-02-08T19:31:02Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 5f74eacbcc7fff707a44d8eb58adaa514cb7dcb5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-14371:latest
instance_id: astropy__astropy-14371
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '5.1'
