base_commit: 9db89e1d8f5e82dc617f9c8cbf303fe23a0632b9
created_at: '2021-12-29T08:49:15Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0fa18d2a2179c92efc22200ed6b3689e66cecf92
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pydicom_1776_pydicom-1555:latest
instance_id: pydicom__pydicom-1555
log_parser: parse_log_pydicom
repo: pydicom/pydicom
split: dev
version: '2.2'
