base_commit: 1abbc0ac3e552cb184317194e5d5c5b9dd8fb640
created_at: '2020-11-17T22:23:42Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: 3ac1464b8840d5f8b618a654f9fbf09c452fe969
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-20442:latest
instance_id: sympy__sympy-20442
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.8'
