base_commit: 7121bdf1facdd90d05b6994b4c2e5b2865a4638a
created_at: '2017-12-19T10:44:38Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Lite
environment_setup_commit: ec9e3c0436fbff934fa84e22bf07f1b3ef5bfac3
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-13773:latest
instance_id: sympy__sympy-13773
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.1'
