base_commit: fc2e0754d9020bb9998bd0bb6ecb459d7f38bd44
created_at: '2023-03-22T23:04:16Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 5f74eacbcc7fff707a44d8eb58adaa514cb7dcb5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-14566:latest
instance_id: astropy__astropy-14566
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '5.1'
