base_commit: f5c5c571d3b87a78d005ea6f21959388d1747696
created_at: '2023-03-25T18:39:07Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 4a72da71001f154ea60906a2f74898d32b7322a7
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16686:latest
instance_id: django__django-16686
log_parser: parse_log_django
repo: django/django
split: test
version: '5.0'
