base_commit: 14abc988525f344d1974c043f83b1e6b1247aea6
created_at: '2019-06-04T17:28:48Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16963:latest
instance_id: sympy__sympy-16963
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
