base_commit: 0e1d299f8f7084b8cb6286caed92e3169317027f
created_at: '2019-03-21T17:59:36Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 2e89d074b3b2abc2da80e437c93b1d5516a0ca57
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-8519:latest
instance_id: astropy__astropy-8519
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '3.1'
