base_commit: a6232c17a6d3c79e95353924df3a3cd062df0708
created_at: '2019-06-02T14:57:30Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-16943:latest
instance_id: sympy__sympy-16943
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
