base_commit: 4fe3774c729f3fd5105b3001fe69a70bdca95ac3
created_at: '2019-12-05T23:03:59Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 475cffd1d64c690cdad16ede4d5e81985738ceb4
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-12187:latest
instance_id: django__django-12187
log_parser: parse_log_django
repo: django/django
split: test
version: '4.0'
