base_commit: 30a0130b463a8b73bed10f707c86fb80cd5eba73
created_at: '2019-07-18T20:06:19Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 70381f282f2d9d039da860e391fe51649df2779d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-17223:latest
instance_id: sympy__sympy-17223
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.5'
