base_commit: 7813fc7f409838fe4c317321fd11c285a98b4ceb
created_at: '2020-12-09T19:42:40Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 3ac1464b8840d5f8b618a654f9fbf09c452fe969
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-20565:latest
instance_id: sympy__sympy-20565
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.8'
