base_commit: d44c83e7cee923869e3ca6149da4e6d1ad0286eb
created_at: '2022-02-13T13:24:21Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: a4dcf3f08d95cbde4efb39969b0ab8e33a791f21
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sqlfluff_1776_sqlfluff-2625:latest
instance_id: sqlfluff__sqlfluff-2625
log_parser: parse_log_sqlfluff
repo: sqlfluff/sqlfluff
split: dev
version: '0.9'
