base_commit: f0f133943d3e4f1e2e665291fe1c8f658a84cc09
created_at: '2023-06-28T21:31:50Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: <15 min fix
environment_setup_commit: 0849036fd992a2dd133a0cffc3f84f58ccf1840f
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.matplotlib_1776_matplotlib-26208:latest
instance_id: matplotlib__matplotlib-26208
log_parser: parse_log_matplotlib
repo: matplotlib/matplotlib
split: test
version: '3.7'
