base_commit: 3f2821af6bc48fa8e7970c1ce27bc54c3172545e
created_at: '2020-07-21T16:40:51Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13218:latest
instance_id: django__django-13218
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
