base_commit: 74fd233b1433da8c68de636172ee1c9c6d1c08c9
created_at: '2020-12-30T02:26:00Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13822:latest
instance_id: django__django-13822
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
