base_commit: 48b6108e50abb1b1f8143721bad8bd7e0be4cc89
created_at: '2022-12-23T12:14:56Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 0fbdb9784da915fce5dcc1fe82bac9b4785749e5
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-16398:latest
instance_id: django__django-16398
log_parser: parse_log_django
repo: django/django
split: test
version: '4.2'
