base_commit: ede9fac75807fe5810df66280a60e7068cc97e4a
created_at: '2020-10-19T15:20:08Z'
datasets:
- SWE-bench/SWE-bench
- SWE-bench/SWE-bench_Verified
difficulty: 15 min - 1 hour
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13568:latest
instance_id: django__django-13568
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
