base_commit: 5e3ed748e2a59e5d72f82d85f871a8a61900ca75
created_at: '2023-06-12T11:22:25Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 362f6df12abf9bd769d4915fabf955c993ea22cf
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.astropy_1776_astropy-14938:latest
instance_id: astropy__astropy-14938
log_parser: parse_log_astropy
repo: astropy/astropy
split: test
version: '5.2'
