base_commit: 78c06e504cf7a9e9d9b2a1c3894a9ccadf2bbbea
created_at: '2019-09-19T14:41:06Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 7e85a6d1f038bbb932b36f18d75df6be937ed00d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.scikit-learn_1776_scikit-learn-15028:latest
instance_id: scikit-learn__scikit-learn-15028
log_parser: parse_log_scikit
repo: scikit-learn/scikit-learn
split: test
version: '0.22'
