base_commit: f386454d1302b66d0eb331ed0ae9e4811e2f3a15
created_at: '2020-06-19T08:28:19Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 65dfb06a1ab56c238cc80f5e1c31f61210c4577d
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.django_1776_django-13085:latest
instance_id: django__django-13085
log_parser: parse_log_django
repo: django/django
split: test
version: '3.2'
