base_commit: 8cb334cf8b0d8f9be490fecf578aca408069b671
created_at: '2021-08-23T08:02:01Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: f9a6f50ec0c74d935c50a6e9c9b2cb0469570d91
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.sympy_1776_sympy-21931:latest
instance_id: sympy__sympy-21931
log_parser: parse_log_sympy
repo: sympy/sympy
split: test
version: '1.9'
