base_commit: dc4c709e9bca44952decdb74d76cf4e62799890a
created_at: '2022-01-29T16:04:04Z'
datasets:
- SWE-bench/SWE-bench
environment_setup_commit: 3b2fbaec045697d53bdd4435e59dbfc2b286df4b
eval_type: pass_and_fail
image: swebench/sweb.eval.x86_64.pylint-dev_1776_pylint-5743:latest
instance_id: pylint-dev__pylint-5743
log_parser: parse_log_pylint
repo: pylint-dev/pylint
split: test
version: '2.13'
